# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "tree-sitter>=0.25",
#   "tree-sitter-language-pack>=0.9",
# ]
# ///
"""
Comment harvester.

Comments are frequently the only place a system's intent is written down.
Code states what happens; comments state why. An ontology needs the why.

This script extracts comments and classifies them by how much domain signal
they tend to carry, so Pass B and Pass C can read the valuable ones instead
of every line of boilerplate.

Important: a comment is strong evidence about INTENT and weak evidence about
CURRENT BEHAVIOUR. Comments drift from the code they describe. Where a comment
contradicts the code, that contradiction is itself a finding — record it as an
open question rather than picking a side.

Usage:
    uv run harvest_comments.py <path> [--json out.json] [--kind rationale]
"""

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

from tree_sitter_language_pack import get_parser

LANGS = {
    ".go": "go", ".py": "python", ".ts": "typescript", ".tsx": "tsx",
    ".js": "javascript", ".java": "java", ".rb": "ruby", ".rs": "rust",
    ".kt": "kotlin", ".cs": "c_sharp", ".php": "php", ".scala": "scala",
    ".sql": "sql", ".yaml": "yaml", ".yml": "yaml",
}

COMMENT_KINDS = {"comment", "line_comment", "block_comment", "doc_comment"}

DECL_KINDS = {
    "type_spec", "type_declaration", "function_declaration", "method_declaration",
    "const_declaration", "var_declaration", "field_declaration", "struct_item",
    "enum_item", "function_item", "class_definition", "function_definition",
    "class_declaration", "interface_declaration", "enum_declaration",
    "type_alias_declaration", "method_definition", "decorated_definition",
}

# Attention markers, including the ones a non-English team actually writes.
FLAG_RE = re.compile(
    r"\b(TODO|FIXME|HACK|XXX|BUG|WARNING|CAUTION|DEPRECATED|WORKAROUND|TEMP|NOTE)\b"
    r"|待確認|待處理|暫時|先這樣|注意|警告|待補|臨時|不要動|別動|坑|陷阱"
    r"|とりあえず|注意|要確認",
    re.I,
)

# Signals that a comment is explaining a decision rather than restating code.
RATIONALE_RE = re.compile(
    r"\b(because|since|so that|otherwise|must|should|require|rule|policy|"
    r"per |as per|according to|spec|contract|agreed|decided|business|"
    r"legal|compliance|billing|invoice|SLA|vendor|partner|upstream|downstream)\b"
    r"|因為|由於|所以|必須|需要|規定|規則|政策|約定|合約|議定|協議|"
    r"業務|計費|對帳|廠商|客戶|上游|下游|規格|標準|不能|禁止|限制",
    re.I,
)

# Boilerplate that carries no domain meaning.
BOILERPLATE_RE = re.compile(
    r"copyright|licen[cs]e|all rights reserved|SPDX-|"
    r"code generated .* do not edit|autogenerated|@generated|"
    r"eslint-|prettier-|nolint|noqa|type:\s*ignore|pylint:|golangci",
    re.I,
)

# Explicit statements that two names are not interchangeable. These go
# straight into vocabulary[].conflict_notes and are the single highest-value
# comment category the harvester finds — which is exactly why precision
# matters more here than anywhere else in this file. A false positive is not
# noise the reader skims past; it lands in the ontology.
#
# The markers split into two tiers because contrastive phrasing is ambient in
# ordinary prose. "Error dropped rather than propagated" contrasts two things
# and says nothing about naming; a single flat pattern list tags it anyway.
#
# STRONG markers assert a naming relationship on their own wording.
STRONG_CONFLICT_RE = re.compile(
    r"\b(not the same|don['’]?t confuse|do not confuse|"
    r"deprecated in favou?r of|legacy name|"
    r"formerly (called|known as)|used to be called|a\.k\.a\.)\b"
    r"|不是同一|不要混用|別混用|不能混用|容易搞混|不要搞混|舊名|舊稱|為準",
    re.I,
)

# WEAK markers are contrastive or equivalence phrasing that only means
# something once there are names being contrasted. They need corroboration.
WEAK_CONFLICT_RE = re.compile(
    r"\b(differs? from|different from|unlike|as opposed to|instead of|"
    r"rather than|renamed|aka|formerly)\b"
    r"|不同於|改名|混用|搞混|等同於|等於|對應到|實際上是|其實是|區別",
    re.I,
)

# What corroborates a weak marker: a naming conflict is by definition about
# names, so require at least two distinct identifier-shaped tokens. Bare
# lowercase English words do not qualify — that is what separates
# "click_id 是否等同於 transaction_id" from "改名會讓所有引用斷掉".
NAME_RE = re.compile(
    r"`[^`\n]+`"                                  # `backticked`
    r"|\b[a-z][a-z0-9]*(?:_[a-z0-9]+)+\b"          # snake_case
    r"|\b[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+\b"          # UPPER_SNAKE
    r"|\b[a-z]+(?:[A-Z][a-z0-9]*)+\b"              # camelCase
    r"|\b[A-Z][a-z0-9]+(?:[A-Z][a-z0-9]*)+\b"      # PascalCase
)

MIN_NAMES_FOR_WEAK_CONFLICT = 2

# Corroboration has to be local. Names scattered elsewhere in a long block say
# nothing about the sentence carrying the marker: a paragraph that mentions
# `axioms` and `snake_case` in passing does not turn "改名會讓所有引用
# 斷掉" into a naming conflict. Requiring marker and names in one sentence is
# what distinguishes a claim about two names from prose that merely contains
# names.
SENTENCE_SPLIT_RE = re.compile(r"[\n。．；;!?]|(?<=[a-z])\.\s")


def names_in(text: str) -> set[str]:
    """Distinct identifier-shaped tokens, used to corroborate a weak marker."""
    return {m.group().strip("`") for m in NAME_RE.finditer(text)}


def is_conflict(text: str) -> bool:
    if STRONG_CONFLICT_RE.search(text) or STRUCTURED_CONFLICT_RE.search(text):
        return True
    return any(
        (WEAK_CONFLICT_RE.search(part) or STRUCTURED_WEAK_CONFLICT_RE.search(part))
        and len(names_in(part)) >= MIN_NAMES_FOR_WEAK_CONFLICT
        for part in SENTENCE_SPLIT_RE.split(text)
    )

# Heuristic for commented-out code rather than prose.
CODE_RE = re.compile(
    r"^\s*(if|for|while|return|func|def|class|import|var|let|const|print|"
    r"console\.|fmt\.|log\.)\b"
    r"|[;{}]\s*$"
    r"|^\s*[\w.]+\s*[:=]=?\s*\S+\s*$"
    r"|^\s*[\w.]+\([^)]*\)\s*;?\s*$"
)

# Structured tags in Javadoc / TSDoc / Sphinx / Doxygen (e.g. @deprecated, @business_rule, :raises:)
STRUCTURED_TAG_RE = re.compile(
    r"(?::|(?<!\w)@)(deprecated|business_rule|businessrule|rule|policy|spec|contract|"
    r"throws|raises|exception|see|alias|link|warning|note|caution|param|returns?)\b",
    re.I,
)

# @deprecated and @alias name a replacement, so they assert a naming
# relationship. @see and @link are generic cross-references that appear on
# most documented symbols, so they only count once names accompany them.
STRUCTURED_CONFLICT_RE = re.compile(
    r"(?::|(?<!\w)@)(deprecated|alias)\b",
    re.I,
)

STRUCTURED_WEAK_CONFLICT_RE = re.compile(
    r"(?::|(?<!\w)@)(see|link)\b",
    re.I,
)

STRUCTURED_RATIONALE_RE = re.compile(
    r"(?::|(?<!\w)@)(business_rule|businessrule|rule|policy|spec|contract|throws|raises|exception|note|warning|caution)\b",
    re.I,
)

SKIP_DIRS = {".git", "node_modules", "vendor", "dist", "build", "target",
             ".venv", "venv", "__pycache__", ".idea", ".vscode", "third_party"}

MARKER_STRIP = re.compile(r"^\s*(///?|#+|/\*+|\*+/?|--|<!--|-->)\s?")


class Block:
    """A run of consecutive single-line comments is one logical comment.
    Classifying each `//` line separately shreds the most valuable artifact
    there is: a multi-line explanation of why something is the way it is."""

    __slots__ = ("start_row", "end_row", "text")

    def __init__(self, start_row, end_row, text):
        self.start_row, self.end_row, self.text = start_row, end_row, text

    @property
    def start_point(self):
        return (self.start_row, 0)

    @property
    def end_point(self):
        return (self.end_row, 0)


def merge_adjacent(nodes) -> list[Block]:
    blocks = []
    for node in sorted(nodes, key=lambda n: n.start_point[0]):
        raw = node.text.decode("utf8", "replace")
        s, e = node.start_point[0], node.end_point[0]
        if blocks and s - blocks[-1].end_row <= 1:
            blocks[-1].text += "\n" + raw
            blocks[-1].end_row = e
        else:
            blocks.append(Block(s, e, raw))
    return blocks


def clean(text: str) -> str:
    lines = [MARKER_STRIP.sub("", ln).rstrip() for ln in text.splitlines()]
    return "\n".join(ln for ln in lines if ln.strip()).strip()


def collect_nodes(root):
    """Flatten the tree once: comments, declarations, and lines carrying
    numeric literals or conditionals."""
    comments, decls, hot_lines = [], [], set()

    def walk(node):
        if node.type in COMMENT_KINDS:
            comments.append(node)
        else:
            if node.type in DECL_KINDS:
                decls.append(node)
            if node.type in {
                "int_literal", "float_literal", "integer", "float",
                "decimal_integer_literal", "number",
            }:
                hot_lines.add(node.start_point[0])
            if node.type in {
                "if_statement", "switch_statement", "expression_switch_statement",
                "type_switch_statement", "conditional_expression", "match_statement",
            }:
                hot_lines.add(node.start_point[0])
        for c in node.children:
            walk(c)

    walk(root)
    return comments, decls, hot_lines


def classify(node, text: str, decls, hot_lines,
             min_lines: int = 5, min_chars: int = 100) -> list[str]:
    """Multi-label on purpose. One comment is often several things at once:
    a doc comment attached to a type, warning about a naming collision, and
    explaining a billing rule. Forcing a single label throws away two thirds
    of what the comment is worth."""
    if not text:
        return ["empty"]
    if BOILERPLATE_RE.search(text):
        return ["boilerplate"]

    body = [ln for ln in text.splitlines() if ln.strip()]
    if body and sum(bool(CODE_RE.search(ln)) for ln in body) / len(body) > 0.6:
        return ["commented_code"]

    tags = []
    start, end = node.start_point[0], node.end_point[0]

    # Doc: sits directly above a declaration or contains structured docstring tags.
    has_structured = bool(STRUCTURED_TAG_RE.search(text))
    is_doc = any(0 <= d.start_point[0] - end <= 1 for d in decls) or has_structured
    if is_doc:
        tags.append("doc")

    # Conflict: states that two names are not interchangeable. See is_conflict
    # for why this is two-tier rather than a single pattern list.
    if is_conflict(text):
        tags.append("conflict")

    # Substantial doc comments are rationale by construction. Nobody writes
    # five lines above a declaration to restate what the declaration says;
    # length is an effort signal, and effort means someone judged the concept
    # worth explaining. This catches teams whose convention is a prose block
    # above every type — a convention that keyword matching would miss
    # entirely, because good explanations often contain no marker words.
    #
    # Line count is the primary test because it is language-neutral. Character
    # count plays two auxiliary roles at the edges:
    #   floor  — reject a line count padded with near-empty lines
    #            (six lines of "// x" is not an explanation)
    #   rescue — accept a dense block that falls under the line threshold
    #            (three lines of solid prose is)
    substantial = False
    if is_doc:
        n_lines = len(body)
        n_chars = len(text.replace("\n", ""))
        # Primary: line count.
        substantial = n_lines > min_lines
        # Auxiliary floor, derived from the line threshold so the two stay in
        # step when it is tuned. 8 chars/line is well below any real sentence.
        if substantial and n_chars < min_lines * 8:
            substantial = False
        # Auxiliary rescue.
        elif not substantial and n_chars > min_chars:
            substantial = True

    # Rationale: sits on or beside a constant or branch — exactly where
    # business intent hides and the code cannot express it — or reads as
    # explanation, or is a substantial doc block, or contains structured rule tags (@business_rule, @throws, :raises:).
    if substantial \
            or any(ln in hot_lines for ln in range(max(0, start - 1), end + 2)) \
            or RATIONALE_RE.search(text) \
            or STRUCTURED_RATIONALE_RE.search(text):
        tags.append("rationale")

    # Flag: an attention marker often records a known business constraint
    # or a deliberate deviation someone had to justify.
    if FLAG_RE.search(text):
        tags.append("flag")

    return tags or ["other"]


# Ordered by how much domain signal the category usually carries.
PRIORITY = {"conflict": 0, "doc": 1, "rationale": 2, "flag": 3, "other": 4,
            "commented_code": 8, "boilerplate": 9, "empty": 9}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("path")
    ap.add_argument("--json", help="write full result here")
    ap.add_argument("--kind", help="filter to one tag: conflict|doc|rationale|flag|other")
    ap.add_argument("--top", type=int, default=40)
    ap.add_argument("--include-noise", action="store_true",
                    help="also emit boilerplate and commented-out code")
    ap.add_argument("--min-doc-lines", type=int, default=5,
                    help="PRIMARY test: a doc comment with more lines than "
                         "this is rationale by construction. Language-neutral.")
    ap.add_argument("--min-doc-chars", type=int, default=100,
                    help="AUXILIARY: rescues a dense block that falls under "
                         "the line threshold. Also sets a floor (min-doc-lines "
                         "x 8) rejecting line counts padded with near-empty "
                         "lines. Language-sensitive — 100 CJK characters is a "
                         "paragraph, 100 Latin characters is one sentence.")
    args = ap.parse_args()

    root = Path(args.path).resolve()
    if not root.exists():
        sys.exit(f"path not found: {root}")

    found, counts = [], defaultdict(int)

    for path in root.rglob("*"):
        if not path.is_file() or any(d in SKIP_DIRS for d in path.parts):
            continue
        lang = LANGS.get(path.suffix.lower())
        if not lang:
            continue
        try:
            src = path.read_bytes()
            tree = get_parser(lang).parse(src)
        except Exception:
            continue

        comments, decls, hot_lines = collect_nodes(tree.root_node)
        blocks = merge_adjacent(comments)
        rel = str(path.relative_to(root))

        for node in blocks:
            # decode already done during merge; CJK survives via replacement
            text = clean(node.text)
            kinds = classify(node, text, decls, hot_lines,
                             args.min_doc_lines, args.min_doc_chars)
            for k in kinds:
                counts[k] += 1
            if set(kinds) & {"boilerplate", "empty", "commented_code"} \
                    and not args.include_noise:
                continue
            body_lines = [ln for ln in text.splitlines() if ln.strip()]
            found.append({
                "kinds": kinds,
                "text": text,
                "file": rel,
                "line": node.start_point[0] + 1,
                "lines": len(body_lines),
                "chars": len(text.replace("\n", "")),
                "symbol_hint": next(
                    (d.text.decode("utf8", "replace").splitlines()[0][:80]
                     for d in decls if 0 <= d.start_point[0] - node.end_point[0] <= 1),
                    None,
                ),
            })

    # Within a priority band, longer comments first: length correlates with
    # how much someone bothered to explain.
    found.sort(key=lambda c: (min(PRIORITY[k] for k in c["kinds"]),
                              -c["chars"], c["file"], c["line"]))
    if args.kind:
        found = [c for c in found if args.kind in c["kinds"]]

    result = {
        "root": str(root),
        "counts": dict(counts),
        "comments": found,
        "note": ("A comment is strong evidence of intent and weak evidence of "
                 "current behaviour. Where a comment contradicts the code, "
                 "record an open question rather than choosing a side."),
    }

    if args.json:
        Path(args.json).write_text(json.dumps(result, indent=2, ensure_ascii=False))
        print(f"wrote {args.json}")

    print(f"\ncounts: {dict(counts)}\n")
    for c in found[: args.top]:
        tags = ",".join(c["kinds"])
        print(f"[{tags:<22}] {c['file']}:{c['line']}  ({c['lines']}L/{c['chars']}c)")
        for ln in c["text"].splitlines()[:4]:
            print(f"{'':<25}{ln[:88]}")
        if c["symbol_hint"]:
            print(f"{'':<25}└ attached to: {c['symbol_hint']}")
        print()


if __name__ == "__main__":
    main()
