description = "Generates a Git commit message based on staged changes."

prompt = """
using following prompt:
```
!{cat ~/vibe-coder/prompts/git_commit.md}
```

codebase diff:
```diff
!{git diff -U5 --staged}
```
"""
